### ISSUE TITLE
Implement subcommands simulate, set_input_log, set_driver_options

### ISSUE THREAD

**Issue by bengtmartensson** [bengtmartensson/PythonLircClient#1]
Neither very hard nor terribly important, but missing to make the implementation "complete".

**Comment by leamas** [comment]
The set_driver_options does not exist as a command in the lircd socket interface and should probably be dropped from this list -- it's just a CLI option to lircd.

**Comment by bengtmartensson** [comment]
Well, the man page lircd(8) mentions it (DRV_OPTIONS). But the list of commands there does not appear exactly to be a well designed interface... SET_INPUTLOG does not appear to be a command that a client should issue to a server. and SIMULATE, well,...

**Comment by leamas** [comment]
I stand corrected. Will implement it in "my" version at least. 

Hell, I wrote this code ;)

**Comment by bengtmartensson** [comment]
Closed by a48afb8. Also renamed set_driver_options -> set_driver_option (singular).
