### ISSUE TITLE
Rename subcommands?

### ISSUE THREAD

**Issue by bengtmartensson** [bengtmartensson/PythonLircClient#10]
In [this PR](https://github.com/bengtmartensson/PythonLircClient/pull/8) it is suggested to rename subcommands with an underscore to similar words, but with a hyphen. @leamas : "justification", reference?

The subcommands are actually not well chosen: "send_once" is an outright lie, unless count = 1. Having "list" perform two different function depending on the number of arguments is not very good, and probably violates some guidelines. This may be the right time to suggest some changes (like Python2 -> Python3?)

Suggestion:
send_once -> send
send_start -> start-send
send_stop -> stop-send
list -> remotes
list <remote> -> commands <remote>
set_transmitters (etc): replace _ by -

Note: no "get" prefix.

Opinions?

**Comment by leamas** [comment]
What I have done in lirctool is 'list-keys' and 'list-remotes' instead of list. "command" is IMHO not that well chosen, "key", "button" or so probably better. Anything along these lines is better than the current state. There is no reason whatsoever to reflect the socket interface in the cli UI.

**Comment by bengtmartensson** [comment]
> "command" is IMHO not that well chosen, "key", "button" or so probably better.

Disagree, "key" (or the synonym "button") simply means something completely different.

> There is no reason whatsoever to reflect the socket interface in the cli UI.

No, there is not. Did anyone claim that?

Leaning towards this:

send_once -> send
send_start -> start
send_stop -> stop
list -> remotes
list -> commands 
set_transmitters -> transmitters
set_input_log -> input-log
set_driver_option -> driver-option
