### ISSUE TITLE
Adopt to common python style

### ISSUE THREAD

**Issue by leamas** [bengtmartensson/PythonLircClient#3]
The python community has their own styleguides, some of which "odd" when coming from other languages. I suggest that the code is checked at least with the pep8 tool and fixed to comply. pylint is also extremely valuable in this context, but needs more setup give meaningful results (the lirc  pylint.conf could be a starter, dunno)

**Comment by bengtmartensson** [comment]
The work is presently a pilot implementation. Your help (PR?) is welcome.

**Comment by leamas** [comment]
Possibly... but not until we have agreed that this is something to be done.

EDIT: In particular, the official style guides are pretty strict about max 80 char linelength. Thoughts?

**Comment by bengtmartensson** [comment]
"A universal convention supplies all of maintainability, clarity, consistency, and a foundation for good programming habits too. What it doesn't do is insist that you follow it against your will. That's Python!"

    —Tim Peters on comp.lang.python, 2001-06-16

Artificially
breaking
"long"
lines
severely
hampers
read-
ability.

Really!
Every line break that logically does not logically belong  to the line is bad (reduces readability)

**Comment by bengtmartensson** [comment]
The issues have been addressed. Let me make a few statements:

* I do not recognize that I "have to" obey any of the "commandments", in particularly not if I consider it unsuitable. So for example, I [reject the official Arduino style guide](https://github.com/bengtmartensson/Infrared4Arduino/blob/master/README.md) (see Coding style), which has not stopped me from having an Arduino library in the official repository.
* The guides, like PEP-8 also are pretty clear that they are not meant to be "commandments".
* Your options are very valuable for me, and I appreciate the discussion. Which is not closed...
