### ISSUE TITLE
Implement packaging

### ISSUE THREAD

**Issue by leamas** [bengtmartensson/PythonLircClient#4]
To make a python tool like this visible is should really be packaged as a pypi package. This also opens up for splitting into a library and a separate script which is "standard procedures" in the python world, allowing pre-compilation etc.

**Comment by bengtmartensson** [comment]
Help welcome.

PS. I changed the title to conform to standard task-based issue titles.

**Comment by bengtmartensson** [comment]
Basically finished with above commits. @leamas : care to give some feedback?

**Comment by leamas** [comment]
As soon as I have pushed 0.10.0 out of the doors I'll update the herctoolbox package. Hopefully, this work should generate some feedback,

**Comment by bengtmartensson** [comment]
@leamas : Your feedback is welcome; however I close the ticket since I consider it finished.
