### ISSUE TITLE
MIssing API documentation

### ISSUE THREAD

**Issue by leamas** [bengtmartensson/PythonLircClient#5]
If the API should be usable it needs to be documented. Part of this is that the code lacks many docstrings. With these in place + some overall file  standard tools lilke sphinx, doxygen or even pydoc can be used to generate the docs

**Comment by bengtmartensson** [comment]
The issue has been addressed. Ok to close?

Feel free to add something relevant to the Makefile, doxygen or some  of the other tools.

**Comment by bengtmartensson** [comment]
> Ok to close?

Neither ACK nor NAK, closing.
