### ISSUE TITLE
Error handling: catching standard exceptions.

### ISSUE THREAD

**Issue by leamas** [bengtmartensson/PythonLircClient#6]
I understand the idea to add info on the used socket name when there is a FileNotFoundException. However, this will utterly fail  if this is raised at some other point. Suggestion: catch exception, print some info and re-raise the original exception. At least, this will show the original point of failure.

Same applies to  PermissionError and ConnectionrRefusedError (common handler?)

**Comment by bengtmartensson** [comment]
Partially disagree. It would have better to catch exceptions from the constructors immediately after calling them; I knew this, basically it was lazyness that I put all the catching at the end.

I would rather say that newLircClient possibly breaks encapsulation by throwing FileNotFoundEncapsulation, ConnectionRefusedError etc.

**Comment by leamas** [comment]
Seems that we agree that it's something to fix, somehow.

**Comment by bengtmartensson** [comment]
Improvements are always welcome, both for fixing real problems and for improving the quality of the code (clarity, efficiency, robustness, etc). But what you call "utterly fail" is nothing but a sub-optimal error message... Thank you for raising the issue.

**Comment by bengtmartensson** [comment]
Your concern has been addressed. OK to close?

**Comment by leamas** [comment]
NP :)
